### ISSUE TITLE
Initial thoughts on How To Learn

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/prework#4]
Initially, I would love to get input from one, or more, Junior Instructors about their perspectives on what "learning how to learn" meant to them as they went through the course. The chapter is in place with some basic content, but it needs much more.

https://github.com/nashville-software-school/prework/blob/phoenix/book-1-your-computer/chapters/HOW_TO_LEARN.md

**Comment by kimberly-bird** [comment]
You thinking in line like this kind of stuff?

1. Learning how to admit that I didn’t know/understand something instead of BSing and pretending that I knew what was going on
1. Being ok knowing that there are gaps in my understanding and being able to continue forward with some big question marks
1. Learning that I am not a video tutorial learner - I always prefer a written tutorial
1. How to give enough context but not too much context when asking questions

**Comment by stevebrownlee** [comment]
Items 1-3 yes, not so much 4. I want the imconing student to get a picture painted of what their learning experience will be like, not much the finer details of how to code or how to ask questions.

**Comment by mscpotts** [comment]
This is the first time I've really used GitHub or looked at the pre-work. Initially, I had trouble following the pre-work as prescribed in the tracker, which was later confirmed by Jeremiah at NSS to be slightly outdated. If that, along with the names of links could be modified/confirmed to match what is prescribed it would clear up a lot of confusion for me. 
I've found the "Smarter Way to learn" to be most helpful and enjoyable so far compared to Odin and at times Treehouse. So much so that I've thought about skipping the latter two and just buying Mark's books for CSS and HTML.
Also, and this may only be because I'm confused on the names of the links and doing way more than I should, but I feel like the huge chunk of Treehouse Digital Literacy track assigned in Step One of the pre-work really slows down the momentum of learning and building code directly.
I've had trouble with my Workspace pages in Treehouse and was directed by Treehouse to ask the community. Since I'm new to coding, the directions didn't make a lot of sense regarding what I was supposed to post for my question, so an in-person source (like a weekly meetup/open-hours tutoring at NSS would be most helpful) to point out why my background color won't change because of error in my code.
I hope these comments help both of us and others!
